### ISSUE TITLE
Forbidden newlines in headers are not allowed

### ISSUE THREAD

**Issue by voillla** [PortSwigger/http-request-smuggler#11]
Due to default Fooz:bar header issued when probing by http smuggler in burp suite, the server returns a 403 error saying "Forbidden: Newlines in headers are not allowed". But when I manually remove the Fooz:bar header line in repeater I get the response correctly. Is there a workaround that this directly work on the tool?

**Comment by albinowax** [comment]
That's an intentional part of the attack.

**Comment by voillla** [comment]
I was trying these on the labs on portswigger.I manually tried solving these labs and I am able to detect the vulnerability.But with the tool, I am not successful. You say this is intentional, what should I do next? Should I try other options than using badLF to get the timeout.
