### ISSUE TITLE
I have some problems. Can you give me some advice?

### ISSUE THREAD

**Issue by yiKnife** [PortSwigger/http-request-smuggler#16]
I read your article and I know how to test request smuggling. But according to your method, send an attacker's request and then send a large number of victim's requests. But when I send a large number of victim's requests, there are some problems. When I use request smuggler(TE.CL) and turbo intruder, it simply sends a large number of attacker's requests. I sent an attacker request like this
![3_LI](https://user-images.githubusercontent.com/40874896/66279487-3c197680-e8e4-11e9-9c3a-e2145222e6c6.JPG)
**When I put this request in the repeater module, it returned 200 ok. But when I attacked**
![4_LI](https://user-images.githubusercontent.com/40874896/66279600-fdd08700-e8e4-11e9-89a9-f5cfa9b10bcd.jpg)
I can't get the 404 result I want. Because all requests are repeated attacker requests, None of them are normal requests. I was really confused. What should I do? How should I use this extension??

**Comment by albinowax** [comment]
The 'Smuggle attack' option is designed to be used on a synced response (ie not an attack). This means the input request should probably look like:
```
Transfer-Encoding: chunked-or-something
Content-Length: 5

0
```


I recommend trying out the labs if you haven't already: https://portswigger.net/web-security/request-smuggling
