### ISSUE TITLE
Unable to install extension via BApp Store

### ISSUE THREAD

**Issue by piyush-saurabh** [PortSwigger/http-request-smuggler#19]
I am trying to install the extension in Burp Suite running on **Windows 10 32 bit**, but the status remains as "_Installing_" but never gets installed. I tried it multiple times, both on Burp Suite Professional and Community version, but no luck.

**Comment by Ajwani97** [comment]
Did you check the packets going out, maybe a firewall's blocking your requests.

**Comment by piyush-saurabh** [comment]
I don't think it is firewall issue because I am able to install the extension on another machine(mac) in the same network

**Comment by albinowax** [comment]
Interesting. Could you report this to support@portswigger.net? Thanks.

**Comment by MichaelEaton-PortSwigger** [comment]
Hi, could it be that you need to configure your upstream proxy in Project Options > Connections? You need to ensure that you can communicate with portswigger.net through port 443 (or 80 if not using HTTPS).

I have just tested this on both macOS & Windows 10 and I can install HTTP Request Smuggler from the BApp store without any issues.

**Comment by piyush-saurabh** [comment]
Hi all,

I am able to install other extensions in burp except this one. I am able to
install this extension on my macos which is in the same network. Did you
try installing on windows 10 32 bit system?

**Comment by piyush-saurabh** [comment]
Thanks Michael
I tried the below command and I am able to install the extension successfully.
java -jar -Xmx1024m burp.jar

**Comment by neal1991** [comment]
same issue here, but for mac. I can install other extension, but this extension keeps installing.
