### ISSUE TITLE
Window resizing for "Attack Config" not enabled.

### ISSUE THREAD

**Issue by Ajwani97** [PortSwigger/http-request-smuggler#20]
The window "Attack Config" when produced by clicking on "Launch Smuggle probe" can't be resized.

**Comment by Ajwani97** [comment]
Can the dialog be made under Hierarchy with a scroll pane, in ConfigurationSettings as described here:

https://benohead.com/java-make-joptionpane-dialog-resizable/

**Comment by Ajwani97** [comment]
![image](https://user-images.githubusercontent.com/55632740/67575578-62387680-f72c-11e9-878f-cfe62428ebff.png)

**Comment by BitTheByte** [comment]
Same problem

**Comment by albinowax** [comment]
I've taken the lazy approach and made the window wider: https://github.com/PortSwigger/http-request-smuggler/commit/6d4978be968cc410001c452d1cd2d800bd78cc94

This update should land in the BApp store edition in about 24 hours.
