### ISSUE TITLE
Scan for smuggling attacks

### ISSUE THREAD

**Issue by laowang1026** [PortSwigger/http-request-smuggler#23]
I am trying to use HTTP to request a smuggler to test a CL.TE experiment, but I can't scan for smuggling
![](https://user-images.githubusercontent.com/45323129/67583706-b66c4680-f77e-11e9-919c-cabb68604e42.png)
![](https://user-images.githubusercontent.com/45323129/67583741-c6842600-f77e-11e9-8e62-8867a40935da.png)

**Comment by albinowax** [comment]
I'm not providing personal support to people using cracked burp...
