### ISSUE TITLE
Menu is too big.

### ISSUE THREAD

**Issue by ChristopherKai** [PortSwigger/http-request-smuggler#28]
![image](https://user-images.githubusercontent.com/3326425/75306994-8c8a7400-5885-11ea-8fd4-395979219a98.png)

The "HTTP Smuggle Probe"menu is too big,I cant even select the "ok" button.

**Comment by albinowax** [comment]
Try ctrl+enter.

Out of interest what resolution are you on?

**Comment by albinowax** [comment]
In fact you can just hit enter to launch the scan.

**Comment by ChristopherKai** [comment]
Thanks,solved.
