### ISSUE TITLE
install fail due to "Failed to verify BApp file"

### ISSUE THREAD

**Issue by xuxiaoyuspallow** [PortSwigger/http-request-smuggler#30]
Either from Bapp store or from mannul, it would always fail because the error
![image](https://user-images.githubusercontent.com/11512396/77150428-d35b3a80-6ace-11ea-9662-e557b841b1eb.png).
When install from mannul, it would poll up an alert window ,as below:
![image](https://user-images.githubusercontent.com/11512396/77150249-6e074980-6ace-11ea-9e50-6bc78a6235da.png)

**Comment by albinowax** [comment]
Interesting. We can't replicate this problem at our end - maybe your network is corrupting the file somehow? Could you:
- Post the md5sum of the manually downloaded bapp file
- Post the head and the tail of the file; it's possible something has been appended/prepended

**Comment by xuxiaoyuspallow** [comment]
I didn't download any bapp file. But I compile it from source code.
reproduce:
1. download source code:
 ```https://github.com/PortSwigger/http-request-smuggler/archive/master.zip```
2. upzip to ``http-request-smuggler`. Then cd to the directory. run:
```gradle fatJar```
3. would get ```http-request-smuggler\build\libs\http-request-smuggler-all.jar```
4. the md5 of the above file is:  `d72599d952c19c06b550e9b2bbfa3c08`

**Comment by xuxiaoyuspallow** [comment]
And all other extensions' installation is good

**Comment by albinowax** [comment]
If you build a jar from source, you need to load it via Extender->Extensions->Add  (not via Extender-BApp Store->Manual install)

**Comment by albinowax** [comment]
To be fair this is pretty unclear from the UI so I've raised a ticket internally.

**Comment by xuxiaoyuspallow** [comment]
> If you build a jar from source, you need to load it via Extender->Extensions->Add (not via Extender-BApp Store->Manual install)

ok, I fixed in this way

**Comment by MarkJaroski** [comment]
I had a similar issue, but it turned out to be the "Disable Java SNI extension" checkbox.
