### ISSUE TITLE
can not find "Smuggle attack" button in right-click menu on request

### ISSUE THREAD

**Issue by chenhb-zte** [PortSwigger/http-request-smuggler#31]
Burp suite version is V2.1.03

Fristly i clicked ‘Launch sumllge probe’, and waited for the probe completed， but i can not find 'Smuggle attack' button in menu on request.

**Comment by mcgyver5** [comment]
I had the same experience and found that Smuggle Attack options only show up if you are using a request that already has both headers in it (you can paste them in):
Transfer-Encoding: chunked
Content-Length: 25 (or whatever number...)
