### ISSUE TITLE
After Launched Smuggle Probe....nothing happens

### ISSUE THREAD

**Issue by Aregaard** [PortSwigger/http-request-smuggler#32]
![Output](https://user-images.githubusercontent.com/16863326/78924865-ca8cd180-7a9a-11ea-8e60-299f903714b7.png)

This might be a big newbie question...but:
System: OSX Catalina and Burp Suite Community.
-I click on the Target-tab and right-click on a www.*****.com-address which was spidered Passive.
-RIght-click on the GET-request and "Launch Smuggle Probe"
- Go to Extender-->Extensions-->Output tab--> UI:
- Nothing shows up. It just says (sometimes) 1 attack in queue. Where can I see the results?

I know how the HTTP Smuggling works in practice. I have been doing it manually, but when I saw this add-on I would like to try it.

**Comment by erwanlr** [comment]
Ran into the same issue. As far as I know, you can not see the attacks (unless maybe via another extension, such as Logger++).

If a probe is successful, the result will be displayed in the `Issues Activity` section of the `Dashboard` tab, as well as `Issues` section of the `Target` tab:

<img width="628" alt="Screenshot 2020-06-23 at 15 31 02" src="https://user-images.githubusercontent.com/1668843/85409872-a8b5cd80-b566-11ea-9b8f-a821c1999dfe.png">

To see if all checks are finished, go to the Extender > Extensions > (Select HTTP Request Snuggler) > Output > Show in UI:
```
Queued 1 attacks
TImeout with response. Start time: 1592916088100 Current time: 1592916208153 Difference: 120053 Tolerance: 10000
Unexpected report with response
Completed 1 of 1
```

If the checks are finished and there is no output in the issue activity, then nothing was detected by the probe
