### ISSUE TITLE
Couldn't find http-request-smuggler-all.jar

### ISSUE THREAD

**Issue by jammyuna** [PortSwigger/http-request-smuggler#33]
Im trying to install http-request-smuggler manually. But I cant find any other jar file except turbo-intruder jar file in the folder. I believe i need http-request-smuggler jar file to complete the installation. Help.

<img width="631" alt="Capture" src="https://user-images.githubusercontent.com/64008910/79938376-0490a700-848f-11ea-9147-42a9595ccd63.PNG">

**Comment by albinowax** [comment]
You need to build the jar with 'gradle build fatjar'

**Comment by albinowax** [comment]
Or you can grab it from https://github.com/PortSwigger/turbo-intruder/releases but I don't always bother updating that...
