### ISSUE TITLE
Smuggle probe running even though task execution paused

### ISSUE THREAD

**Issue by infosecconsultant** [PortSwigger/http-request-smuggler#35]
Hi, 

I’ve ‘globally’ paused task extensions as well as all the blow audits/crawls as shown below. However, using the extension logger++ the smuggle probe extension is clearly generating new traffic regardless at the same rate as before.

Logger++ reports the source of the traffic as ‘extender’.

All tasks paused
![image](https://user-images.githubusercontent.com/48705722/84636609-1bf08b80-af38-11ea-9123-29095e07a7dc.png)

Pause happened at request 26. Note that it continues (and will persist)
![image](https://user-images.githubusercontent.com/48705722/84637692-59a1e400-af39-11ea-91cc-672c8cee8fb2.png)

Unloading the extension stops the smuggle probe task, but it can not be resumed and instead must start again.

The config I used was as shown below, however, it does not appear to matter which options are used:
![image](https://user-images.githubusercontent.com/48705722/84637552-2c553600-af39-11ea-9060-c7d3452db152.png)

If there is some way to pause the execution of the smuggle probe that would be possible to resume, that would be most welcome. 

In a similar vein, being able to see that the smuggle probe is running, and specifically, what host it is running against would be a most welcome additional feature. 

Thanks,

**Comment by albinowax** [comment]
Unfortunately this is a core Burp issue affecting all extensions, and isn't something I can fix. It should be resolved in core Burp eventually.

You could potentially implement a pause button for all extensions in Distribute Damage. Personally it doesn't fit into my use case so it's not a priority unfortunately.
