### ISSUE TITLE
flow tab not showing

### ISSUE THREAD

**Issue by nocomp** [PortSwigger/http-request-smuggler#4]
hi,
just tried this plugn, and the flow tab is not showing, so can t be used.
using 2.1.03 beta

best regards

**Comment by securitygeneration** [comment]
Same here. Testing on macOS Catalina 10.15 Beta (19A526h).

**Comment by albinowax** [comment]
The flow tab is created by the Flow extension. It's not required - I just used it for the demo to show the underlying behaviour. You can install flow via the BApp store.
