### ISSUE TITLE
Recieveing Null Response Smuggler

### ISSUE THREAD

**Issue by hellotry** [PortSwigger/http-request-smuggler#40]
Hi,

Burp extension and smuggler tool both indicated the http request smuggler (CL.TE) vulnerability, but when i test the vulnerability through turbo intruder i got null response.

Is there any mistake in payload? Even i have not received any 404 or redirection, just received a null.

![null](https://user-images.githubusercontent.com/22060123/87240017-02efd300-c42f-11ea-8003-8e79220ddc3e.png)

**Comment by hellotry** [comment]
Kindly someone respond please on this issue.

Thanks.

**Comment by albinowax** [comment]
A 'null' response occurs when the server reset the connection without responding.  This could mean pretty much anything.
