### ISSUE TITLE
 The CL.TE attack payload is missing a newline character

### ISSUE THREAD

**Issue by superboy-zjc** [PortSwigger/http-request-smuggler#42]
When using CL.TE to attack the module, I found that there is only one newline after the 0 terminator of the data block, and it should be two newlines under normal circumstances.
![image](https://user-images.githubusercontent.com/60600792/106541048-25b51680-653c-11eb-960b-efdc3f4ea832.png)

**Comment by superboy-zjc** [comment]
In addition, you can see that the newline input through Turbo Intruder lacks ”/r“, which leads to the failure of the attack.
![image](https://user-images.githubusercontent.com/60600792/106541768-87c24b80-653d-11eb-8961-553db18328c1.png)

**Comment by albinowax** [comment]
Thanks for the report. Which operating system are you using?

**Comment by albinowax** [comment]
As a pointer, my guess is that this is occurring because you're using an OS that uses \n as line-endings, and you have defined your injection using a multi-line string. You can work around this by adding .replace('\n','\r\n') on the end of the injection string.

**Comment by superboy-zjc** [comment]
> Thanks for the report. Which operating system are you using?

Windows 10

**Comment by superboy-zjc** [comment]
> As a pointer, my guess is that this is occurring because you're using an OS that uses \n as line-endings, and you have defined your injection using a multi-line string. You can work around this by adding .replace('\n','\r\n') on the end of the injection string.

thanks for your solution!

**Comment by albinowax** [comment]
I've patched this now: https://github.com/PortSwigger/http-request-smuggler/commit/165815a6d0e2f79dab72369974784ccb8615336a
