### ISSUE TITLE
Not working against burpsuite lab

### ISSUE THREAD

**Issue by cristianocca** [PortSwigger/http-request-smuggler#44]
I have been testing the extension against https://portswigger.net/web-security/request-smuggling/finding/lab-confirming-te-cl-via-differential-responses

I launch the extension from right clicking on a request, and then select "Smuggle Probe".  Wait a while, and the results are always the same:
```
Queued 1 attacks from 1 requests in 0 seconds
Completed 4 of 4 with 820 requests, 0 candidates and 0 findings 
```

No findings at all.

Ideas?

**Comment by albinowax** [comment]
I can't replicate this; it works fine for me. Can you try using the 'reset settings' button, disabling any other extensions you may have installed, and scanning the homepage again.

**Comment by cristianocca** [comment]
This was from a fresh install. Also, this was executed from an EC2 instance in AWS (VM in the cloud), not sure if the fact that the code is running in a VM may affect burpsuite or the extension.

Manually sending the solution payload worked though.

**Comment by albinowax** [comment]
Interesting. Unfortunately without sufficient information so replicate this I can't fix it.
