### ISSUE TITLE
Smuggle Probe Fails To Detect the Vulnerability on Basic Web Academy Lab

### ISSUE THREAD

**Issue by FahadSec** [PortSwigger/http-request-smuggler#52]
I have Burp Suite Professional Version 2022.5.2 on Mac OS. 

I attempted to test the HTTP Request Smuggler Probe on the PortSwigger Web Academy Request Smuggler Lab 1: [HTTP request smuggling, basic CL.TE vulnerability](https://portswigger.net/web-security/request-smuggling/lab-basic-cl-te) but the extension failed to detect it. I tried unloading all my extensions and it still didn't work.

Attached the request logs.

[smuggler_logs.csv](https://github.com/PortSwigger/http-request-smuggler/files/8993267/smuggler_logs.csv)

**Comment by albinowax** [comment]
Thanks for the report, this was really useful. I've investigated and found an issue with the lab which has now been resolved, so you should find this works now.

**Comment by FahadSec** [comment]
I can confirm it works now. Thank you. 

Also I'm not sure if this behavior is intended, but I was only notified about the vulnerability through the _Target_ section. The output in the extender tab said there are 0 findings.
```
Using albinowaxUtils v1.03
This extension should be run on the latest version of Burp Suite. Using an older version of Burp may cause impaired functionality.
Loaded HTTP Request Smuggler v2.03
Updating active thread pool size to 8
Loop 0
Queued 1 attacks from 1 requests in 0 seconds
Unexpected report with response
Completed 0a0000fd04f27257c05af7e800ef000c.web-security-academy.net: 1 of 1 in 33 seconds with 25 requests, 0 candidates and 0 findings 
```

**Comment by albinowax** [comment]
Good to hear it's fixed. Yeah those stats are not very accurate, nothing to worry about.
