### ISSUE TITLE
Connection-state scan fails in community edition

### ISSUE THREAD

**Issue by justblock6** [PortSwigger/http-request-smuggler#57]
Whenever I try to use the "Connection-state" testing, I receive this error right away 
```
Error in thread: Cannot invoke "burp.IBurpCollaboratorClientContext.generatePayload(boolean)" because "burp.BasicCollab.collab" is null
```
Is Burp Pro/Collab needed for this scan?

**Comment by albinowax** [comment]
Ah sorry it uses three techniques and one of them assumes you have pro and breaks the whole check. I'll get that fixed ASAP

**Comment by albinowax** [comment]
I've just pushed a fix for this, so if you build from source it should work now. The change should be released into the bapp store within a few days. Thanks for the report!
