### ISSUE TITLE
Timeout option not working

### ISSUE THREAD

**Issue by plenumlab** [PortSwigger/http-request-smuggler#6]
It seems like the timeout setting is not working i set it to 10 but it does not have any effect on the waiting time.

**Comment by albinowax** [comment]
The timeout setting in HTTP Request Smuggler affects the delay after which it considers a response to be a timeout. If you want to change how long Burp actually waits for a response to arrive, you need to change Burp's timeout in the network options.

**Comment by plenumlab** [comment]
Yes, but it doesn't do that even the server timeout after 50 seconds or so

**Comment by albinowax** [comment]
HTTP Request Smuggler isn't designed to report an issue on every timeout, as that would cause false positives. As far as I can tell the timeout setting works as intended so I can't help with a test case.
