### ISSUE TITLE
Engine warming up..

### ISSUE THREAD

**Issue by MochaCocoa** [PortSwigger/http-request-smuggler#63]
After I installed the Http-request-smuggler plug-in using burp suite,When I click on CL.TE attack，it keep reminding Engine warming up, After waiting for ten minutes, it still doesn't work.
![image](https://github.com/PortSwigger/http-request-smuggler/assets/42690209/5099cffd-cab4-4f0b-91d6-f25f156055bf)
![image](https://github.com/PortSwigger/http-request-smuggler/assets/42690209/e716eda4-40d4-4230-b7dd-4967bed36e7d)
![image](https://github.com/PortSwigger/http-request-smuggler/assets/42690209/d7380c06-c3f0-4a58-868c-0d5fb9c5eca0)

**Comment by joshdesharnais1** [comment]
I have the same issue while working through there practice lab listed in the readme.md. My burp is update to the most recent as of today.

**Comment by albinowax** [comment]
@joshdesharnais1 if you can provide the following info, I'll be able to take a look:
- Which specific lab are you looking at?
- Screenshot of the vulnerability as reported by HTTP Request Smuggler
- Screenshot of the turbo intruder script
- Your version of Burp Suite, and HTTP Request Smuggler

**Comment by tstOutpost24** [comment]
I have also come across this recently. Interestingly, copying whatever script doesn't work with request smuggler, and pasting it into turbo intruder (with exactly the same request to run against) works great! It's just that the request smuggler window get's stuck at "Engine warming up..."

I tried this using version 2023.10.3.2-24372 (early adopter) and 2023.10.2.4 (Stable).

**Comment by albinowax** [comment]
@tstOutpost24 thanks, that's useful info.

I can see the problem now, working on a fix

**Comment by albinowax** [comment]
I've pushed a fix in release 2.16, thanks for reporting!
