### ISSUE TITLE
"Smuggle attack" uses "Connection: keep-alive" even when issue was detected with "Connection: close"

### ISSUE THREAD

**Issue by alex-birsan** [PortSwigger/http-request-smuggler#8]
Hi!

I'm not quite sure if this is intended, but I've noticed that all attacks launched through the "Smuggle attack" option will issue requests with "Connection: keep-alive", even if the original detection mentions "closed" as a requirement.

Steps to reproduce:

* Scan any target that produces a finding ending in `closed`
* Right-click the issue -> Smuggle Attack -> Attack
* Notice that the attack request contains a "Connection: keep-alive" header

Is this something that could impact findings, or is it intended/unimportant?

Thanks,
Alex

**Comment by albinowax** [comment]
This is by design. The timeout-based detection runs faster with `Connection: close`, but that header can prevent the followup attack from working so it's automatically rewritten.
